language: objective-c

osx_image: xcode7.3

podfile: ABCFrameWork/Podfile

before_install:
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'

script: 
- xctool -workspace ABCFrameWork/ABCFrameWork.xcworkspace -scheme ABCFrameWork -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- travis_wait 40 xctool -workspace ABCFrameWork/ABCFrameWork.xcworkspace -scheme ABCFrameWorkTests test -sdk iphonesimulator